routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@dashboard')->name('dashboard');
Route::get('replays/{replay}/show', 'ReplayController@show')->name('replays.show');
Route::get('replays/{replay}/download', 'ReplayController@download')->name('replays.download');

Route::group([
    'prefix' => 'u',
    'as' => 'u.',
    'namespace' => 'User',
    'middleware' => ['auth']
], function () {
    Route::get('replays/create', 'ReplayController@create')->name('replays.create');
    Route::post('replays/store', 'ReplayController@store')->name('replays.store');
    Route::get('replays/{replay}/edit', 'ReplayController@edit')->name('replays.edit');
    Route::put('replays/{replay}/update', 'ReplayController@update')->name('replays.update');
});

app/Replay.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Plank\Mediable\Mediable;


/**
 * Class Replay
 * @package App
 * @mixin \Eloquent
 */
class Replay extends Model
{
    use Mediable;

    protected $fillable = [
        'lev_name',
        'rec_name',
        'token',
        'legit',
        'description',
        'finished',
        'duration',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Scope for TAS recs
     *
     * @param type $query
     * @param type $levelName
     * @return type
     */
    public function scopeTas($query)
    {
        return $query->where('legit', false);
    }

    /**
     * Scope for legit recs
     *
     * @param type $query
     * @param type $levelName
     * @return type
     */
    public function scopeLegit($query)
    {
        return $query->where('legit', true);
    }

    /**
     * Scope for filtering results with exact or approximate level filename
     *
     * @param type $query
     * @param type $levelName
     * @return type
     */
    public function scopeLevelLike($query, $levelName)
    {
        return $query->where('lev_name', 'like', "%$levelName%");
    }

    /**
     * Accessor for getting created at attribute
     *
     * @param $value
     * @return Carbon
     */
    public function getCreatedAtAttribute($value)
    {
        return Carbon::parse($value);
    }

    /**
     * Accessor for getting lev url attribute
     *
     * @return string
     */
    public function getLevUrlAttribute()
    {
        return $this->firstMedia('lev')->getUrl();
    }

    /**
     * Accessor for getting rec url attribute
     *
     * @return string
     */
    public function getRecUrlAttribute()
    {
        return $this->firstMedia('rec')->getUrl();
    }


    /**
     * Check if the current user has permission to this replay
     *
     * @return bool
     */
    public function userHasPermission()
    {
        return auth()->user() && (
                auth()->user()->id === $this->user->id ||
                auth()->user()->id === 1);
    }
}

resources/views/partials/recplay-container.blade.php
<div class="panel-body rec p-4" id="recplay-container">
    <div id="recplay"
         data-levurl="{{ $replay->levurl }}"
         data-recurl="{{ $replay->recurl }}"></div>
</div>

resources/views/partials/replay-filter-form.blade.php
{{ csrf_field() }}

<div class="form-group">
    <label class="mr-1" for="level">
        Level
        <input type="text" id="level" name="level" class="form-control" value={{ request()->input('level') }}>
    </label>

    <label class="mr-1" for="uploader">
        Uploader
        <input type="text" id="uploader" name="uploader" class="form-control" value="{{ request()->input('uploader') }}">
    </label>

    <label class="mr-1" for="type">
        Type
        <select name="type" id="type" class="form-control">
            <option {{ (int) request()->input('type') !== 1 || (int) request()->input('type') !== 2 ? 'selected' : ''}}></option>
            <option value="1" {{ (int) request()->input('type') === 1 ? 'selected' : ''}}>Legit</option>
            <option value="2" {{ (int) request()->input('type') === 2 ? 'selected' : ''}}>TAS</option>
        </select>
    </label>
    <button type="submit" class="btn btn-primary mr-1" style="margin-bottom: 2px">Submit</button>
    <button type="button" class="btn btn-secondary js-replay-filter-form-clear" style="margin-bottom: 2px">Clear</button>
</div>

resources/views/partials/replay-header.blade.php
<div class="panel-heading p-4"><h1 class="replay-title">{{ $replay->rec_name }} @unless ($replay->legit)
    <span class="legit tas-flag--large pull-right">TAS</span> @endunless</h1>

    <div class="replay-header">
        <div>
            @if ($replay->description)
                <p class="replay-header__description">{{ $replay->description }}</p>
            @endif

            <p class="m-0">
                Uploaded by: {{ $replay->user->name }} <br> {{ $replay->created_at }} <br>
            </p>

            <a href="{{ route('replays.download', $replay) }}"><span class="glyphicon glyphicon-download-alt"></span> Download rec</a>
        </div>

        <div class="replay-header__right">
            @if ($replay->userHasPermission())
                <a class="btn btn-primary" href="{{ route('u.replays.edit', $replay) }}">Edit</a>
            @endif

            <p style="margin: 0; text-align: end">Duration: <b class="numeric">
                    {{ $replay->finished ?
                    mstostrtime($replay->duration, 3) :
                    mstostrtime($replay->duration, 2) }}
                </b>
            </p>
        </div>
    </div>
</div>

resources/views/partials/replay-list.blade.php
<div class="container">
    <div class="row px-4 pb-5 mb-5">
        <div class="col-md-10 col-md-offset-1">
            <ul class="replay-list m-0 p-0 js-replay-list">
                @foreach ($replays as $replayItem)
                    <li class="replay-list__item">
                        <a class="js-load-replay replay-list__link{{ (isset($replay) && $replayItem->id === $replay->id) ? ' replay-list__link--active' : ''}}"
                           href="{{ route('replays.show', [
                                $replayItem,
                                'rec_name' => $replayItem->rec_name,
                                'level' => request()->input('level'),
                                'uploader' => request()->input('uploader'),
                                'type' => request()->input('type'),
                            ]) }}">
                            <div class="replay-list__recname">
                                {{ str_limit($replayItem->rec_name, 16) }}
                            </div>

                            <div class="replay-list__levname">
                                {{ $replayItem->lev_name }}
                            </div>

                            <div class="replay-list__username">
                                {{ $replayItem->user->name }}
                            </div>

                            <div class="replay-list__time">
                                @if ($replayItem->finished)
                                    <span class="numeric">
                                        {{ mstostrtime($replayItem->duration, 2) }}
                                    </span>
                                @else
                                    <span>DNF</span>
                                @endif
                            </div>

                            <div class="replay-list__createdat">
                                {{ $replayItem->created_at->diffForHumans() }}
                            </div>

                            <div class="replay-list__legit pr-2">
                                @unless ($replayItem->legit) <span class="legit">TAS</span> @endunless
                            </div>
                        </a>
                    </li>
                @endforeach
            </ul>
        </div>
    </div>
</div>