routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@dashboard')->name('dashboard');
Route::get('replays/{replay}/show', 'ReplayController@show')->name('replays.show');
Route::get('replays/{replay}/download', 'ReplayController@download')->name('replays.download');

Route::group([
    'prefix' => 'u',
    'as' => 'u.',
    'namespace' => 'User',
    'middleware' => ['auth']
], function () {
    Route::get('replays/create', 'ReplayController@create')->name('replays.create');
    Route::post('replays/store', 'ReplayController@store')->name('replays.store');
    Route::get('replays/{replay}/edit', 'ReplayController@edit')->name('replays.edit');
    Route::put('replays/{replay}/update', 'ReplayController@update')->name('replays.update');
});

app/Replay.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Plank\Mediable\Mediable;


/**
 * Class Replay
 * @package App
 * @mixin \Eloquent
 */
class Replay extends Model
{
    use Mediable;

    protected $fillable = [
        'lev_name',
        'rec_name',
        'token',
        'legit',
        'description',
        'finished',
        'duration',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Scope for TAS recs
     *
     * @param type $query
     * @param type $levelName
     * @return type
     */
    public function scopeTas($query)
    {
        return $query->where('legit', false);
    }

    /**
     * Scope for legit recs
     *
     * @param type $query
     * @param type $levelName
     * @return type
     */
    public function scopeLegit($query)
    {
        return $query->where('legit', true);
    }

    /**
     * Scope for filtering results with exact or approximate level filename
     *
     * @param type $query
     * @param type $levelName
     * @return type
     */
    public function scopeLevelLike($query, $levelName)
    {
        return $query->where('lev_name', 'like', "%$levelName%");
    }

    /**
     * Accessor for getting created at attribute
     *
     * @param $value
     * @return Carbon
     */
    public function getCreatedAtAttribute($value)
    {
        return Carbon::parse($value);
    }

    /**
     * Accessor for getting lev url attribute
     *
     * @return string
     */
    public function getLevUrlAttribute()
    {
        return $this->firstMedia('lev')->getUrl();
    }

    /**
     * Accessor for getting rec url attribute
     *
     * @return string
     */
    public function getRecUrlAttribute()
    {
        return $this->firstMedia('rec')->getUrl();
    }


    /**
     * Check if the current user has permission to this replay
     *
     * @return bool
     */
    public function userHasPermission()
    {
        return auth()->user() && (
                auth()->user()->id === $this->user->id ||
                auth()->user()->id === 1);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function replays()
    {
        return $this->hasMany(Replay::class);
    }
}

app/Http/Controllers/ReplayController.php
<?php

namespace App\Http\Controllers;

use App\Replay;
use Illuminate\Http\Request;

class ReplayController extends Controller
{
    /**
     * Show the replay
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View|\Illuminate\Http\JsonResponse
     */
    public function show(Request $request, $replayId)
    {
        $replay = Replay::find($replayId);

        $replaysQuery = \App\Replay::orderBy('replays.id', 'desc')
            ->select('replays.*')
            ->with('user');

        $replays = \App\Services\Replay::filterByRequest($request, $replaysQuery);

        if ($request->wantsJson()) {
            $recplayContainerRendered = view()->make('partials/recplay-container', compact('replay'))->render();
            $replayListRendered = view()->make('partials/replay-list', compact('replay', 'replays'))->render();
            $replayHeaderRendered = view()->make('partials/replay-header', compact('replay'))->render();

            return response()->json([
                'replay_list' => $replayListRendered,
                'recplay_container' => $recplayContainerRendered,
                'replay_header' => $replayHeaderRendered,
                'rec_name' => $replay->rec_name,
                'rec_url' => $replay->recurl,
                'lev_url' => $replay->levurl,
                'app_title' => implode(' - ', [
                    config('app.name', 'Laravel'),
                    $replay->rec_name
                ]),
            ]);
        }

        return view('replays.show', compact('replay', 'replays'));
    }

    public function download($replayId)
    {
        $replay = Replay::find($replayId);

        return response()->download($replay->firstMedia('rec')->getAbsolutePath());
    }
}

app/Http/Controllers/User/ReplayController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Services\LevelDownloader;
use App\Replay;
use App\Rec\Rec;
use Illuminate\Http\Request;
use MediaUploader;

class ReplayController extends Controller
{
    /**
     * Show the rec upload form
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('user.replays.create');
    }

    /**
     * Store a replay
     *
     * @param Replay $replay
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Replay $replay, Request $request)
    {
        $request->validate([
            'file' => 'required',
            'legit' => 'boolean',
            'description' => 'string|nullable',
        ]);

        if ($request->file('file')) {
            /* store the file into the filesystem and create media */
            $recMedia = MediaUploader::fromSource($request->file('file'))
                ->upload();

            $levName = Rec::extractLevName($recMedia->getAbsolutePath());

            $request->validate([
                'file' => function($attribute, $value, $fail) use($request) {
                    $fileName = pathinfo($request->file('file')->getClientOriginalName(), PATHINFO_FILENAME);
                    $replayWithSameName = Replay::where('rec_name', $fileName)->first();

                    if ($replayWithSameName) {
                        return $fail("Rec with name {$fileName} already exists");
                    }
                },
            ]);

            $crc = Rec::extractCRC($recMedia->getAbsolutePath());

            if (($downloader = LevelDownloader::findMatchingLevel($levName, $crc))->getStatus()) {
                $levMedia = MediaUploader::importPath('public', implode(DIRECTORY_SEPARATOR, [
                    $downloader->getTempDirectory(),
                    $levName,
                ]));
            } else {
                return redirect()->route('u.replays.create');
            }

            $recInfo = Rec::recInfo($recMedia->getAbsolutePath());

            $replay = user()->replays()->create([
                'lev_name' => $levMedia->filename,
                'rec_name' => $recMedia->filename,
                'legit' => $request->input('legit'),
                'description' => $request->input('description'),
                'finished' => $recInfo->finished,
                'duration' => $recInfo->duration,
            ]);

            /* attach the media into the Replay model */
            $replay->attachMedia($recMedia, 'rec');
            $replay->attachMedia($levMedia, 'lev');

            $recMedia->move(implode(DIRECTORY_SEPARATOR, [
                'replays',
                $replay->id,
                'rec'
            ]));

            $levMedia->move(implode(DIRECTORY_SEPARATOR, [
                'replays',
                $replay->id,
                'rec'
            ]));

            return redirect()->route('replays.show', [
                $replay,
                $replay->rec_name,
            ]);
        }
    }

    public function edit(int $replayId)
    {
        $replay = Replay::find($replayId);

        if (! $replay->userHasPermission()) {
            return back();
        }

        return view('user.replays.edit', compact('replay'));
    }

    public function update(int $replayId, Request $request)
    {
        $replay = Replay::find($replayId);

        if (! $replay->userHasPermission()) {
            return back();
        }

        $validatedData = $request->validate([
            'legit' => 'boolean',
            'description' => 'string|nullable',
        ]);

        $replay->update($validatedData);

        return redirect()->route('replays.show', [
            $replay,
            $replay->rec_name,
        ]);
    }
}

resources/views/user/replays/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Upload</div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ route('u.replays.store') }}" enctype="multipart/form-data"> 
                        {{ csrf_field() }}                       
                        <div class="form-group{{ $errors->has('file') ? ' has-error' : '' }}">
                            <label for="file" class="col-md-4 control-label">File</label>

                            <div class="col-md-6">
                                <input id="file" type="file" class="form-control" name="file" value="{{ old('file') }}" required autofocus>

                                @if ($errors->has('file'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('file') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                            <label for="description" class="col-md-4 text-right">Description</label>
                            <div class="col-md-6">
                                <textarea class="form-control" name="description" id="description" cols="40" rows="5">{{ old('description', '') }}</textarea>
                            </div>

                            @if ($errors->has('description'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('description') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group{{ $errors->has('file') ? ' has-error' : '' }}">
                            <label for="legit" class="col-md-4 text-right">TAS</label>
                            <div class="col-md-6">
                                <input type="hidden" value="1" name="legit">
                                <input type="checkbox" id="legit" name="legit" value="{{ old('legit', 0)  }}" class="checkbox-inline">
                            </div>

                            @if ($errors->has('legit'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('legit') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Upload
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/replays/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Edit</div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ route('u.replays.update', $replay) }}">
                        <input name="_method" type="hidden" value="PUT">

                        {{ csrf_field() }}
                        <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                            <label for="description" class="col-md-4 text-right">Description</label>
                            <div class="col-md-6">
                                <textarea class="form-control" name="description" id="description" cols="40" rows="5">{{ $replay->description }}</textarea>
                            </div>

                            @if ($errors->has('description'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('description') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group{{ $errors->has('legit') ? ' has-error' : '' }}">
                            <label for="legit" class="col-md-4 text-right">TAS</label>
                            <div class="col-md-6">
                                <input type="hidden" value="1" name="legit">
                                <input class="checkbox-inline" type="checkbox" id="legit" name="legit" value="{{ old('legit', 0)  }}" {{ $replay->legit === 0 ? 'checked' : '' }}>
                            </div>

                            @if ($errors->has('legit'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('legit') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Update
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection